### ISSUE TITLE
[xp30] [xq30] Typo in section D Implementation-Defined Items

### ISSUE THREAD

**Issue by rhdunn** [w3c/qtspecs#10]
In https://www.w3.org/TR/xpath-30/#id-impl-defined-items, item 13 has the text:
> Any serialization parameters provided by the implementationn

`implementationn` should be `implementation`, and there should be a `.` at the end of the sentence.

In https://www.w3.org/TR/xquery-30/#id-impl-defined-items, item 23 has the text:
> Any serialization parameters provided by the implementation (see 2.2.4 Serialization).n

there is a stray `n` at the end of the item sentence.

**Comment by michaelhkay** [comment]
This has been fixed in the 3.1 specs. No-one is going to be correcting trivial errors in the superseded 3.0 specs at this stage of the game.
