### ISSUE TITLE
[xslt30] xsl:for-each-group/@composite description typo

### ISSUE THREAD

**Issue by ToshihikoMakita** [w3c/qtspecs#28]
`xsl:for-each-group/@composite` is described as follows:

[https://github.com/w3c/qtspecs/blob/master/specifications/xslt-30/html/xslt30.xml](https://github.com/w3c/qtspecs/blob/master/specifications/xslt-30/html/xslt30.xml)

````xml
<phrase diff="chg" at="G">If <code>composite="yes"</code> is specified, there is
   a single grouping key whose value is the resulting sequence; otherwise, there is a set of
   grouping keys, consisting of the distinct atomic values present in the result
   sequence.</phrase>
````

From its original meaning, I guessed `composite="yes"` should be written as `composite="no"`.

I have tested with Saxon implementation (HE 9.9.1.7) and when `composite="no"` and `@group-adjacent` returns more than one items, the transformation ended with following error message:

````
[xslt] D:\DITA-OT\dita-ot-3.6.1\plugins\com.antennahouse.pdf5.ml\xsl\dita2fo_indexcommon_index_out.xsl:242:32: Fatal Error! A sequence of more than one item is not allowed as the @group-adjacent attribute of xsl:for-each-group ("#all", "1", ...) 
````

According to the actual implementation result, I think `composite="yes"` is a typo of  `composite="no"`.

Regards,

**Comment by michaelhkay** [comment]
I think the spec is correct.

The error you are seeing is described in the spec: _[ERR XTTE1100] It is a type error if the result of evaluating the group-adjacent expression is an empty sequence or a sequence containing more than one item, unless composite="yes" is specified._

Perhaps it could have been better explained.

- With group-by, composite=no, an item can be added to more than one group: each value of the grouping key is considered individually, so if the key is ("France", "Germany") then the item is added to both the France group and the Germany group.
 
- With group-by, composite=yes, each item is added to exactly one group: so if the key is ("France", "Germany") then the item is added to the group of items having the key ("France", "Germany").
 
- With group-adjacent, composite="no", the grouping key must be a single item, or XTTE1100 results.

- With group-adjacent, composite="yes", each item is added to exactly one group: so if the key is ("France", "Germany") then the item is added to the group of adjacent items having the key ("France", "Germany").

I hope that clarifies.

**Comment by ToshihikoMakita** [comment]
Thank you for your clarification. The explanation is concrete. I was reading the specification without the deep consideration about the key and the  results.
