### ISSUE TITLE
[xp31] [xq31] The attributes axis references the parent accessor.

### ISSUE THREAD

**Issue by rhdunn** [w3c/qtspecs#29]
The axes section (https://www.w3.org/TR/xpath-31/#axes) states;
> the attribute axis contains the attributes of the context node, which are the nodes returned by the Section 5.11 parent Accessor DM31; the axis will be empty unless the context node is an element

This should reference the attributes selector (`dm:attriibutes`).

**Comment by michaelhkay** [comment]
Fixed in the draft 4.0 specification.
