### ISSUE TITLE
[fo31] Incorrect note regarding fn:collation-key()

### ISSUE THREAD

**Issue by michaelhkay** [w3c/qtspecs#3]
In F&O 3.1, the notes for fn:collation-key() say:

> This specification does not mandate that collation keys should retain ordering. This is partly because the primary use case is for maps, where only equality comparisons are required, and partly to allow the use of binary data types (which are currently unordered types) for the result. The specification may be revised in a future release to specify that ordering is preserved. 

This paragraph is incorrect and should be deleted. The spec does now mandate that fn:collation-key() is order-preserving, and binary data types are now ordered, which was done specifically to make this possible.

**Comment by Divyab082** [comment]
URL mallumonika

**Comment by Divyab082** [comment]
https://github.com/w3c/qtspecs/issues/3#issuecomment-917709224

**Comment by Divyab082** [comment]
![Uploading -5hz8uq.jpg…]()

**Comment by michaelhkay** [comment]
The paragraph has been deleted from the 4.0 draft.
