### ISSUE TITLE
[xslt4] Compact syntax

### ISSUE THREAD

**Issue by stefan-jung** [w3c/qtspecs#60]
It would be nice, if XSLT4 would have a non-XML (compact) syntax, similar to the [RELAX NG Compact Syntax](https://www.oasis-open.org/committees/relax-ng/compact-20021121.html).

**Comment by michaelhkay** [comment]
There have been a number of attempts to do this, none of which achieved widespread adoption. Doing it well involves significant challenges. I would suggest doing a design and publishing it, perhaps at a conference such as Balisage or XML Prague, and then submitting the idea for standardisation when you have a complete proposal. Note that active specification work on XSLT 4.0 takes place at https://github.com/qt4cg/qtspecs and you would need to put the proposal on the table there. But don't expect the idea to be considered unless you are prepared to do most of the work yourself.

**Comment by stefan-jung** [comment]
Thank you, @michaelhkay.
