### ISSUE TITLE
### Microsoft PowerToys version

### ISSUE THREAD

**Issue by mutebmuhd1403** [w3c/qtspecs#65]
### Microsoft PowerToys version

0.81.0

### Installation method

PowerToys auto-update

### Running as admin

None

### Area(s) with issue?

Advanced Paste

### Steps to reproduce

I attach a video the shows the behaviour. On Windows, when i have closed slack into systray and then open a chat window, all clipboard data is automatically inserted into slack. Even files i have copied in file explorer. 

This does not happen when i just minimize to task bar instead of systray.

I do not press any key. Just open with a click on the systray icon.

The only plugin i have activated is Advanced Paste (Screenshot bellow). If i disable just this plugin or close power toys, the auto insert is gone.

This started immediately after todays update to 0.81.0.

This behaviour can lead to serious data breach if you do not pay attention.

[powertoys.webm](https://github.com/microsoft/PowerToys/assets/1684236/c4d22e6b-df77-47e1-a1ea-1b238d8dda76)

![image](https://github.com/microsoft/PowerToys/assets/1684236/c7a6e9f6-2f0d-431f-abf1-5b4d2eec60f3)

### ✔️ Expected Behavior

No auto insert in any application.

### ❌ Actual Behavior

Auto insert with just focusing a window....

### Other Software

Slack

### Report
[PowerToysReport_2024-05-22-13-13-02.zip](https://github.com/microsoft/PowerToys/files/15402385/PowerToysReport_2024-05-22-13-13-02.zip)

_Originally posted by @brainfoolong in https://github.com/microsoft/PowerToys/issues/32971_

**Comment by michaelhkay** [comment]
Closed as spam.
