### ISSUE TITLE
### Description of the new feature / enhancement

### ISSUE THREAD

**Issue by mutebmuhd1403** [w3c/qtspecs#66]
### Description of the new feature / enhancement

It would be nice to have a tool to convert the selected text to a different format (CamelCase, UPPERCASE, lowercase, Snake_Case, Kebab-Case, no spaces between words, no spaces at the beginning and end of the string).

### Scenario when this would be used?

When textis selected, via the right click context menu have a subcategory with the various types of text that can be converted.
In powertoys settings add the ability to disable unnecessary ones.

### Supporting information

Maybe in powertoys settings give the ability to add custom templates via regex.

_Originally posted by @ProvaTeams in https://github.com/microsoft/PowerToys/issues/34059_

**Comment by michaelhkay** [comment]
Closed as spam.
